(() => {
  'use strict';
  const KEY = 'm2y_enhancement_dashboard';
  const fallback = { theme: 'light', density: 'normal', favoriteView: 'overview', notes: '', lastSeen: 0, activity: [] };
  const store = { async get(){ try { if (globalThis.chrome?.storage?.local) return {...fallback,...(await chrome.storage.local.get(KEY))[KEY]}; } catch(_){} try{return {...fallback,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(_){return {...fallback}} }, async set(v){try{if(globalThis.chrome?.storage?.local)return chrome.storage.local.set({[KEY]:v})}catch(_){} try{localStorage.setItem(KEY,JSON.stringify(v))}catch(_){}} };
  const q = s => document.querySelector(s); const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function getData(){try{return globalThis.chrome?.storage?.local ? await chrome.storage.local.get(null) : {}}catch(_){return {}}}
  function countLeads(data){return Object.entries(data).filter(([k,v]) => /^leads_/.test(k) && Array.isArray(v)).reduce((n,[,v])=>n+v.length,0)}
  function metricCards(total,data){const leads=Object.entries(data).filter(([k,v])=>/^leads_/.test(k)&&Array.isArray(v)).flatMap(([,v])=>v);const reviewed=leads.filter(x=>x.reviewed||x.revisado).length;const phones=leads.filter(x=>x.phone||x.telefone).length;const digital=leads.filter(x=>x.website||x.site||x.facebook||x.instagram).length;const screenshots=leads.filter(x=>/^data:image\/(jpeg|jpg|png);base64,/.test(String(x.screenshot||''))).length;return `<div class="m2y-mini-metrics"><div><b>${total}</b><span>leads totais</span></div><div><b>${reviewed}</b><span>revisados</span></div><div><b>${total?Math.round(phones/total*100):0}%</b><span>com telefone</span></div><div><b>${total?Math.round(digital/total*100):0}%</b><span>presença digital</span></div><div><b>${total?Math.round(screenshots/total*100):0}%</b><span>screenshot válido</span></div></div>`}
  async function render(state){const data=await getData(); const total=countLeads(data); const box=q('#m2yDashboardEnhancements'); if(!box)return; const lastUpdate=state.lastSeen?new Date(state.lastSeen).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'Ainda não visitado'; box.innerHTML=`<div class="m2y-dash-head"><div><strong>Central de operação</strong><span>Atualizado: ${lastUpdate}</span></div><div class="m2y-dash-actions"><button id="m2yNewSearch">＋ Nova busca</button><button id="m2yRefresh">↻ Atualizar</button><button id="m2yCopySummary">▣ Copiar resumo</button><button id="m2yDashTheme">◐ Tema</button></div></div>${metricCards(total,data)}<div class="m2y-dash-grid"><div class="m2y-empty-state ${total?'has-data':''}"><b>${total?'Dados prontos para análise':'Comece sua primeira extração'}</b><p>${total?'Use os atalhos para revisar, filtrar ou exportar seus leads.':'Abra a tela inicial, informe categoria e cidade e inicie uma extração. Seus resultados aparecerão aqui.'}</p><div><button id="m2yOpenLeads">Ver leads</button><button id="m2yOpenSearch">Abrir busca</button></div></div><div class="m2y-health"><b>Saúde do sistema</b><span>Armazenamento: <em>disponível</em></span><span>Leads carregados: <em>${total}</em></span><span>Última atualização: <em>${lastUpdate}</em></span></div></div><div class="m2y-dash-lower"><div><b>Atividade recente</b><div class="m2y-activity">${state.activity.length?state.activity.slice(0,5).map(a=>`<span>${esc(a.text)} <small>${new Date(a.at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></span>`).join(''):'Nenhuma atividade registrada ainda.'}</div></div><div><b>Notas rápidas</b><textarea id="m2yDashNotes" placeholder="Anote um próximo passo ou contexto local...">${esc(state.notes)}</textarea><button id="m2ySaveNotes">Salvar nota</button></div></div>`;
    q('#m2yNewSearch').onclick=()=>window.open('../popup/popup.html','_blank'); q('#m2yOpenSearch').onclick=()=>window.open('../popup/popup.html','_blank'); q('#m2yOpenLeads').onclick=()=>q('[data-view="leads"]')?.click(); q('#m2yRefresh').onclick=async()=>{state.lastSeen=Date.now();state.activity.unshift({text:'Dashboard atualizado',at:Date.now()});await store.set(state);render(state)}; q('#m2yDashTheme').onclick=async()=>{state.theme=state.theme==='dark'?'light':'dark';document.body.classList.toggle('m2y-theme-dark',state.theme==='dark');await store.set(state);}; q('#m2yCopySummary').onclick=async()=>{const text=`M2y — ${total} leads\nRevisados: ${document.querySelector('.m2y-mini-metrics div:nth-child(2) b')?.textContent||0}\nAtualizado: ${lastUpdate}`;try{await navigator.clipboard.writeText(text)}catch(_){};announce('Resumo copiado')}; q('#m2ySaveNotes').onclick=async()=>{state.notes=q('#m2yDashNotes').value;state.activity.unshift({text:'Nota rápida salva',at:Date.now()});await store.set(state);announce('Nota salva')};
  }
  function announce(t){const e=q('#m2yDashLive');if(e)e.textContent=t}
  async function init(){if(q('#m2yDashboardEnhancements'))return;const state=await store.get();document.body.classList.toggle('m2y-theme-dark',state.theme==='dark');const overview=q('#overviewView');if(!overview)return;const box=document.createElement('section');box.id='m2yDashboardEnhancements';box.className='m2y-dashboard-enhancement panel-card';overview.insertBefore(box,overview.querySelector('.chart-container'));const live=document.createElement('div');live.id='m2yDashLive';live.className='sr-only';live.setAttribute('aria-live','polite');document.body.appendChild(live);render(state);document.addEventListener('keydown',e=>{if(e.key==='?'&&!e.ctrlKey&&!e.metaKey){announce('Atalhos: N nova busca, L leads, R atualizar');}if(e.key.toLowerCase()==='n'&&!e.target.matches('input,textarea'))q('#m2yNewSearch')?.click();if(e.key.toLowerCase()==='l'&&!e.target.matches('input,textarea'))q('#m2yOpenLeads')?.click();if(e.key.toLowerCase()==='r'&&!e.target.matches('input,textarea'))q('#m2yRefresh')?.click()});state.lastSeen=Date.now();await store.set(state)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
